CREATE TABLE Users (
	`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(24) NOT NULL UNIQUE,
	`password` VARCHAR(1024) NOT NULL,
	`email` VARCHAR(256) NOT NULL,
	`bio` VARCHAR(256) NOT NULL
);
CREATE TABLE Sessions (
	`id` VARCHAR(256) NOT NULL UNIQUE,
	`userid` INT(11) REFERENCES Users(id) UNIQUE
)