CREATE TABLE Users (
	`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(24) NOT NULL,
	`password` VARCHAR(1024) NOT NULL,
	`email` VARCHAR(256) NOT NULL,
	`bio` VARCHAR(256) NOT NULL
);
